import { map, zip, ofArray } from "../../fable_modules/fable-library.4.1.4/List.js";
import { equals } from "../../fable_modules/fable-library.4.1.4/Util.js";
import { PreferenceResponse, Project_get_Default } from "../../../../Shared/Shared.fs.js";
import { Model } from "./PreferencesTypes.fs.js";
import { toList } from "../../fable_modules/fable-library.4.1.4/Seq.js";
import { rangeDouble } from "../../fable_modules/fable-library.4.1.4/Range.js";

export function checkPreferenceChange(model) {
    const p = model.preference;
    const up = model.unsavedPreference;
    const pList = ofArray([p.p1.pid, p.p2.pid, p.p3.pid, p.p4.pid, p.p5.pid, p.p6.pid, p.p7.pid, p.p8.pid, p.p9.pid, p.p10.pid]);
    const upList = ofArray([up.p1.pid, up.p2.pid, up.p3.pid, up.p4.pid, up.p5.pid, up.p6.pid, up.p7.pid, up.p8.pid, up.p9.pid, up.p10.pid]);
    const nList = ofArray([p.n1, p.n2, p.n3, p.n4, p.n5, p.n6, p.n7, p.n8, p.n9, p.n10]);
    const unList = ofArray([up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10]);
    if ((!equals(pList, upList) ? true : !equals(nList, unList)) ? true : (p.comments !== up.comments)) {
        return true;
    }
    else {
        return p.doc !== up.doc;
    }
}

export function removePreference(model) {
    let inputRecord, inputRecord_1, inputRecord_2, inputRecord_3, inputRecord_4, inputRecord_5, inputRecord_6, inputRecord_7, inputRecord_8, inputRecord_9;
    const rank = model.selectedProjectIndex | 0;
    const newModel = new Model(model.loading, model.preference, model.unsavedPreference, model.preferenceEqualList, model.token, Project_get_Default(), 0, model.confirmAddProjectModal, false, model.confirmSaveChangesModal, model.isPreferenceTab);
    switch (rank) {
        case 1:
            return new Model(newModel.loading, newModel.preference, (inputRecord = newModel.unsavedPreference, new PreferenceResponse(inputRecord.eeid, Project_get_Default(), inputRecord.p2, inputRecord.p3, inputRecord.p4, inputRecord.p5, inputRecord.p6, inputRecord.p7, inputRecord.p8, inputRecord.p9, inputRecord.p10, inputRecord.n1, inputRecord.n2, inputRecord.n3, inputRecord.n4, inputRecord.n5, inputRecord.n6, inputRecord.n7, inputRecord.n8, inputRecord.n9, inputRecord.n10, inputRecord.s1, inputRecord.s2, inputRecord.s3, inputRecord.s4, inputRecord.s5, inputRecord.s6, inputRecord.s7, inputRecord.s8, inputRecord.s9, inputRecord.s10, inputRecord.upddate, inputRecord.comments, inputRecord.feedback, inputRecord.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 2:
            return new Model(newModel.loading, newModel.preference, (inputRecord_1 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_1.eeid, inputRecord_1.p1, Project_get_Default(), inputRecord_1.p3, inputRecord_1.p4, inputRecord_1.p5, inputRecord_1.p6, inputRecord_1.p7, inputRecord_1.p8, inputRecord_1.p9, inputRecord_1.p10, inputRecord_1.n1, inputRecord_1.n2, inputRecord_1.n3, inputRecord_1.n4, inputRecord_1.n5, inputRecord_1.n6, inputRecord_1.n7, inputRecord_1.n8, inputRecord_1.n9, inputRecord_1.n10, inputRecord_1.s1, inputRecord_1.s2, inputRecord_1.s3, inputRecord_1.s4, inputRecord_1.s5, inputRecord_1.s6, inputRecord_1.s7, inputRecord_1.s8, inputRecord_1.s9, inputRecord_1.s10, inputRecord_1.upddate, inputRecord_1.comments, inputRecord_1.feedback, inputRecord_1.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 3:
            return new Model(newModel.loading, newModel.preference, (inputRecord_2 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_2.eeid, inputRecord_2.p1, inputRecord_2.p2, Project_get_Default(), inputRecord_2.p4, inputRecord_2.p5, inputRecord_2.p6, inputRecord_2.p7, inputRecord_2.p8, inputRecord_2.p9, inputRecord_2.p10, inputRecord_2.n1, inputRecord_2.n2, inputRecord_2.n3, inputRecord_2.n4, inputRecord_2.n5, inputRecord_2.n6, inputRecord_2.n7, inputRecord_2.n8, inputRecord_2.n9, inputRecord_2.n10, inputRecord_2.s1, inputRecord_2.s2, inputRecord_2.s3, inputRecord_2.s4, inputRecord_2.s5, inputRecord_2.s6, inputRecord_2.s7, inputRecord_2.s8, inputRecord_2.s9, inputRecord_2.s10, inputRecord_2.upddate, inputRecord_2.comments, inputRecord_2.feedback, inputRecord_2.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 4:
            return new Model(newModel.loading, newModel.preference, (inputRecord_3 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_3.eeid, inputRecord_3.p1, inputRecord_3.p2, inputRecord_3.p3, Project_get_Default(), inputRecord_3.p5, inputRecord_3.p6, inputRecord_3.p7, inputRecord_3.p8, inputRecord_3.p9, inputRecord_3.p10, inputRecord_3.n1, inputRecord_3.n2, inputRecord_3.n3, inputRecord_3.n4, inputRecord_3.n5, inputRecord_3.n6, inputRecord_3.n7, inputRecord_3.n8, inputRecord_3.n9, inputRecord_3.n10, inputRecord_3.s1, inputRecord_3.s2, inputRecord_3.s3, inputRecord_3.s4, inputRecord_3.s5, inputRecord_3.s6, inputRecord_3.s7, inputRecord_3.s8, inputRecord_3.s9, inputRecord_3.s10, inputRecord_3.upddate, inputRecord_3.comments, inputRecord_3.feedback, inputRecord_3.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 5:
            return new Model(newModel.loading, newModel.preference, (inputRecord_4 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_4.eeid, inputRecord_4.p1, inputRecord_4.p2, inputRecord_4.p3, inputRecord_4.p4, Project_get_Default(), inputRecord_4.p6, inputRecord_4.p7, inputRecord_4.p8, inputRecord_4.p9, inputRecord_4.p10, inputRecord_4.n1, inputRecord_4.n2, inputRecord_4.n3, inputRecord_4.n4, inputRecord_4.n5, inputRecord_4.n6, inputRecord_4.n7, inputRecord_4.n8, inputRecord_4.n9, inputRecord_4.n10, inputRecord_4.s1, inputRecord_4.s2, inputRecord_4.s3, inputRecord_4.s4, inputRecord_4.s5, inputRecord_4.s6, inputRecord_4.s7, inputRecord_4.s8, inputRecord_4.s9, inputRecord_4.s10, inputRecord_4.upddate, inputRecord_4.comments, inputRecord_4.feedback, inputRecord_4.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 6:
            return new Model(newModel.loading, newModel.preference, (inputRecord_5 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_5.eeid, inputRecord_5.p1, inputRecord_5.p2, inputRecord_5.p3, inputRecord_5.p4, inputRecord_5.p5, Project_get_Default(), inputRecord_5.p7, inputRecord_5.p8, inputRecord_5.p9, inputRecord_5.p10, inputRecord_5.n1, inputRecord_5.n2, inputRecord_5.n3, inputRecord_5.n4, inputRecord_5.n5, inputRecord_5.n6, inputRecord_5.n7, inputRecord_5.n8, inputRecord_5.n9, inputRecord_5.n10, inputRecord_5.s1, inputRecord_5.s2, inputRecord_5.s3, inputRecord_5.s4, inputRecord_5.s5, inputRecord_5.s6, inputRecord_5.s7, inputRecord_5.s8, inputRecord_5.s9, inputRecord_5.s10, inputRecord_5.upddate, inputRecord_5.comments, inputRecord_5.feedback, inputRecord_5.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 7:
            return new Model(newModel.loading, newModel.preference, (inputRecord_6 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_6.eeid, inputRecord_6.p1, inputRecord_6.p2, inputRecord_6.p3, inputRecord_6.p4, inputRecord_6.p5, inputRecord_6.p6, Project_get_Default(), inputRecord_6.p8, inputRecord_6.p9, inputRecord_6.p10, inputRecord_6.n1, inputRecord_6.n2, inputRecord_6.n3, inputRecord_6.n4, inputRecord_6.n5, inputRecord_6.n6, inputRecord_6.n7, inputRecord_6.n8, inputRecord_6.n9, inputRecord_6.n10, inputRecord_6.s1, inputRecord_6.s2, inputRecord_6.s3, inputRecord_6.s4, inputRecord_6.s5, inputRecord_6.s6, inputRecord_6.s7, inputRecord_6.s8, inputRecord_6.s9, inputRecord_6.s10, inputRecord_6.upddate, inputRecord_6.comments, inputRecord_6.feedback, inputRecord_6.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 8:
            return new Model(newModel.loading, newModel.preference, (inputRecord_7 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_7.eeid, inputRecord_7.p1, inputRecord_7.p2, inputRecord_7.p3, inputRecord_7.p4, inputRecord_7.p5, inputRecord_7.p6, inputRecord_7.p7, Project_get_Default(), inputRecord_7.p9, inputRecord_7.p10, inputRecord_7.n1, inputRecord_7.n2, inputRecord_7.n3, inputRecord_7.n4, inputRecord_7.n5, inputRecord_7.n6, inputRecord_7.n7, inputRecord_7.n8, inputRecord_7.n9, inputRecord_7.n10, inputRecord_7.s1, inputRecord_7.s2, inputRecord_7.s3, inputRecord_7.s4, inputRecord_7.s5, inputRecord_7.s6, inputRecord_7.s7, inputRecord_7.s8, inputRecord_7.s9, inputRecord_7.s10, inputRecord_7.upddate, inputRecord_7.comments, inputRecord_7.feedback, inputRecord_7.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 9:
            return new Model(newModel.loading, newModel.preference, (inputRecord_8 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_8.eeid, inputRecord_8.p1, inputRecord_8.p2, inputRecord_8.p3, inputRecord_8.p4, inputRecord_8.p5, inputRecord_8.p6, inputRecord_8.p7, inputRecord_8.p8, Project_get_Default(), inputRecord_8.p10, inputRecord_8.n1, inputRecord_8.n2, inputRecord_8.n3, inputRecord_8.n4, inputRecord_8.n5, inputRecord_8.n6, inputRecord_8.n7, inputRecord_8.n8, inputRecord_8.n9, inputRecord_8.n10, inputRecord_8.s1, inputRecord_8.s2, inputRecord_8.s3, inputRecord_8.s4, inputRecord_8.s5, inputRecord_8.s6, inputRecord_8.s7, inputRecord_8.s8, inputRecord_8.s9, inputRecord_8.s10, inputRecord_8.upddate, inputRecord_8.comments, inputRecord_8.feedback, inputRecord_8.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        case 10:
            return new Model(newModel.loading, newModel.preference, (inputRecord_9 = newModel.unsavedPreference, new PreferenceResponse(inputRecord_9.eeid, inputRecord_9.p1, inputRecord_9.p2, inputRecord_9.p3, inputRecord_9.p4, inputRecord_9.p5, inputRecord_9.p6, inputRecord_9.p7, inputRecord_9.p8, inputRecord_9.p9, Project_get_Default(), inputRecord_9.n1, inputRecord_9.n2, inputRecord_9.n3, inputRecord_9.n4, inputRecord_9.n5, inputRecord_9.n6, inputRecord_9.n7, inputRecord_9.n8, inputRecord_9.n9, inputRecord_9.n10, inputRecord_9.s1, inputRecord_9.s2, inputRecord_9.s3, inputRecord_9.s4, inputRecord_9.s5, inputRecord_9.s6, inputRecord_9.s7, inputRecord_9.s8, inputRecord_9.s9, inputRecord_9.s10, inputRecord_9.upddate, inputRecord_9.comments, inputRecord_9.feedback, inputRecord_9.doc)), newModel.preferenceEqualList, newModel.token, newModel.selectedProject, newModel.selectedProjectIndex, newModel.confirmAddProjectModal, newModel.confirmRemoveProjectModal, newModel.confirmSaveChangesModal, newModel.isPreferenceTab);
        default:
            return newModel;
    }
}

export function swapUp(model, rank) {
    const up = model.unsavedPreference;
    const newUp = (rank === 2) ? (new PreferenceResponse(up.eeid, up.p2, up.p1, up.p3, up.p4, up.p5, up.p6, up.p7, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 3) ? (new PreferenceResponse(up.eeid, up.p1, up.p3, up.p2, up.p4, up.p5, up.p6, up.p7, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 4) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p4, up.p3, up.p5, up.p6, up.p7, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 5) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p5, up.p4, up.p6, up.p7, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 6) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p4, up.p6, up.p5, up.p7, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 7) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p4, up.p5, up.p7, up.p6, up.p8, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 8) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p4, up.p5, up.p6, up.p8, up.p7, up.p9, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 9) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p4, up.p5, up.p6, up.p7, up.p9, up.p8, up.p10, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : ((rank === 10) ? (new PreferenceResponse(up.eeid, up.p1, up.p2, up.p3, up.p4, up.p5, up.p6, up.p7, up.p8, up.p10, up.p9, up.n1, up.n2, up.n3, up.n4, up.n5, up.n6, up.n7, up.n8, up.n9, up.n10, up.s1, up.s2, up.s3, up.s4, up.s5, up.s6, up.s7, up.s8, up.s9, up.s10, up.upddate, up.comments, up.feedback, up.doc)) : up))))))));
    return new Model(model.loading, model.preference, newUp, model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab);
}

export function swapDown(model, rank) {
    return swapUp(model, rank + 1);
}

export function getPreferenceEqualList(pref) {
    const prefs = ofArray([pref.n2, pref.n3, pref.n4, pref.n5, pref.n6, pref.n7, pref.n8, pref.n9, pref.n10]);
    const indexes = toList(rangeDouble(2, 1, 10));
    const list = zip(prefs, indexes);
    return map((tupledArg) => {
        const pref_1 = tupledArg[0] | 0;
        const index = tupledArg[1] | 0;
        return pref_1 !== index;
    }, list);
}

export function updatePreferenceRanks(_arg1_, _arg1__1, _arg1__2, isPrefEqual) {
    let inputRecord, inputRecord_1, inputRecord_2, inputRecord_3, inputRecord_4, inputRecord_5, inputRecord_6, inputRecord_7, inputRecord_8;
    const _arg = [_arg1_, _arg1__1, _arg1__2];
    const prevRank = _arg[2] | 0;
    const model = _arg[0];
    const iter = _arg[1] | 0;
    const rank = (isPrefEqual ? prevRank : iter) | 0;
    switch (iter) {
        case 2:
            return [new Model(model.loading, model.preference, (inputRecord = model.unsavedPreference, new PreferenceResponse(inputRecord.eeid, inputRecord.p1, inputRecord.p2, inputRecord.p3, inputRecord.p4, inputRecord.p5, inputRecord.p6, inputRecord.p7, inputRecord.p8, inputRecord.p9, inputRecord.p10, inputRecord.n1, rank, inputRecord.n3, inputRecord.n4, inputRecord.n5, inputRecord.n6, inputRecord.n7, inputRecord.n8, inputRecord.n9, inputRecord.n10, inputRecord.s1, inputRecord.s2, inputRecord.s3, inputRecord.s4, inputRecord.s5, inputRecord.s6, inputRecord.s7, inputRecord.s8, inputRecord.s9, inputRecord.s10, inputRecord.upddate, inputRecord.comments, inputRecord.feedback, inputRecord.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 3, rank];
        case 3:
            return [new Model(model.loading, model.preference, (inputRecord_1 = model.unsavedPreference, new PreferenceResponse(inputRecord_1.eeid, inputRecord_1.p1, inputRecord_1.p2, inputRecord_1.p3, inputRecord_1.p4, inputRecord_1.p5, inputRecord_1.p6, inputRecord_1.p7, inputRecord_1.p8, inputRecord_1.p9, inputRecord_1.p10, inputRecord_1.n1, inputRecord_1.n2, rank, inputRecord_1.n4, inputRecord_1.n5, inputRecord_1.n6, inputRecord_1.n7, inputRecord_1.n8, inputRecord_1.n9, inputRecord_1.n10, inputRecord_1.s1, inputRecord_1.s2, inputRecord_1.s3, inputRecord_1.s4, inputRecord_1.s5, inputRecord_1.s6, inputRecord_1.s7, inputRecord_1.s8, inputRecord_1.s9, inputRecord_1.s10, inputRecord_1.upddate, inputRecord_1.comments, inputRecord_1.feedback, inputRecord_1.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 4, rank];
        case 4:
            return [new Model(model.loading, model.preference, (inputRecord_2 = model.unsavedPreference, new PreferenceResponse(inputRecord_2.eeid, inputRecord_2.p1, inputRecord_2.p2, inputRecord_2.p3, inputRecord_2.p4, inputRecord_2.p5, inputRecord_2.p6, inputRecord_2.p7, inputRecord_2.p8, inputRecord_2.p9, inputRecord_2.p10, inputRecord_2.n1, inputRecord_2.n2, inputRecord_2.n3, rank, inputRecord_2.n5, inputRecord_2.n6, inputRecord_2.n7, inputRecord_2.n8, inputRecord_2.n9, inputRecord_2.n10, inputRecord_2.s1, inputRecord_2.s2, inputRecord_2.s3, inputRecord_2.s4, inputRecord_2.s5, inputRecord_2.s6, inputRecord_2.s7, inputRecord_2.s8, inputRecord_2.s9, inputRecord_2.s10, inputRecord_2.upddate, inputRecord_2.comments, inputRecord_2.feedback, inputRecord_2.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 5, rank];
        case 5:
            return [new Model(model.loading, model.preference, (inputRecord_3 = model.unsavedPreference, new PreferenceResponse(inputRecord_3.eeid, inputRecord_3.p1, inputRecord_3.p2, inputRecord_3.p3, inputRecord_3.p4, inputRecord_3.p5, inputRecord_3.p6, inputRecord_3.p7, inputRecord_3.p8, inputRecord_3.p9, inputRecord_3.p10, inputRecord_3.n1, inputRecord_3.n2, inputRecord_3.n3, inputRecord_3.n4, rank, inputRecord_3.n6, inputRecord_3.n7, inputRecord_3.n8, inputRecord_3.n9, inputRecord_3.n10, inputRecord_3.s1, inputRecord_3.s2, inputRecord_3.s3, inputRecord_3.s4, inputRecord_3.s5, inputRecord_3.s6, inputRecord_3.s7, inputRecord_3.s8, inputRecord_3.s9, inputRecord_3.s10, inputRecord_3.upddate, inputRecord_3.comments, inputRecord_3.feedback, inputRecord_3.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 6, rank];
        case 6:
            return [new Model(model.loading, model.preference, (inputRecord_4 = model.unsavedPreference, new PreferenceResponse(inputRecord_4.eeid, inputRecord_4.p1, inputRecord_4.p2, inputRecord_4.p3, inputRecord_4.p4, inputRecord_4.p5, inputRecord_4.p6, inputRecord_4.p7, inputRecord_4.p8, inputRecord_4.p9, inputRecord_4.p10, inputRecord_4.n1, inputRecord_4.n2, inputRecord_4.n3, inputRecord_4.n4, inputRecord_4.n5, rank, inputRecord_4.n7, inputRecord_4.n8, inputRecord_4.n9, inputRecord_4.n10, inputRecord_4.s1, inputRecord_4.s2, inputRecord_4.s3, inputRecord_4.s4, inputRecord_4.s5, inputRecord_4.s6, inputRecord_4.s7, inputRecord_4.s8, inputRecord_4.s9, inputRecord_4.s10, inputRecord_4.upddate, inputRecord_4.comments, inputRecord_4.feedback, inputRecord_4.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 7, rank];
        case 7:
            return [new Model(model.loading, model.preference, (inputRecord_5 = model.unsavedPreference, new PreferenceResponse(inputRecord_5.eeid, inputRecord_5.p1, inputRecord_5.p2, inputRecord_5.p3, inputRecord_5.p4, inputRecord_5.p5, inputRecord_5.p6, inputRecord_5.p7, inputRecord_5.p8, inputRecord_5.p9, inputRecord_5.p10, inputRecord_5.n1, inputRecord_5.n2, inputRecord_5.n3, inputRecord_5.n4, inputRecord_5.n5, inputRecord_5.n6, rank, inputRecord_5.n8, inputRecord_5.n9, inputRecord_5.n10, inputRecord_5.s1, inputRecord_5.s2, inputRecord_5.s3, inputRecord_5.s4, inputRecord_5.s5, inputRecord_5.s6, inputRecord_5.s7, inputRecord_5.s8, inputRecord_5.s9, inputRecord_5.s10, inputRecord_5.upddate, inputRecord_5.comments, inputRecord_5.feedback, inputRecord_5.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 8, rank];
        case 8:
            return [new Model(model.loading, model.preference, (inputRecord_6 = model.unsavedPreference, new PreferenceResponse(inputRecord_6.eeid, inputRecord_6.p1, inputRecord_6.p2, inputRecord_6.p3, inputRecord_6.p4, inputRecord_6.p5, inputRecord_6.p6, inputRecord_6.p7, inputRecord_6.p8, inputRecord_6.p9, inputRecord_6.p10, inputRecord_6.n1, inputRecord_6.n2, inputRecord_6.n3, inputRecord_6.n4, inputRecord_6.n5, inputRecord_6.n6, inputRecord_6.n7, rank, inputRecord_6.n9, inputRecord_6.n10, inputRecord_6.s1, inputRecord_6.s2, inputRecord_6.s3, inputRecord_6.s4, inputRecord_6.s5, inputRecord_6.s6, inputRecord_6.s7, inputRecord_6.s8, inputRecord_6.s9, inputRecord_6.s10, inputRecord_6.upddate, inputRecord_6.comments, inputRecord_6.feedback, inputRecord_6.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 9, rank];
        case 9:
            return [new Model(model.loading, model.preference, (inputRecord_7 = model.unsavedPreference, new PreferenceResponse(inputRecord_7.eeid, inputRecord_7.p1, inputRecord_7.p2, inputRecord_7.p3, inputRecord_7.p4, inputRecord_7.p5, inputRecord_7.p6, inputRecord_7.p7, inputRecord_7.p8, inputRecord_7.p9, inputRecord_7.p10, inputRecord_7.n1, inputRecord_7.n2, inputRecord_7.n3, inputRecord_7.n4, inputRecord_7.n5, inputRecord_7.n6, inputRecord_7.n7, inputRecord_7.n8, rank, inputRecord_7.n10, inputRecord_7.s1, inputRecord_7.s2, inputRecord_7.s3, inputRecord_7.s4, inputRecord_7.s5, inputRecord_7.s6, inputRecord_7.s7, inputRecord_7.s8, inputRecord_7.s9, inputRecord_7.s10, inputRecord_7.upddate, inputRecord_7.comments, inputRecord_7.feedback, inputRecord_7.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 10, rank];
        case 10:
            return [new Model(model.loading, model.preference, (inputRecord_8 = model.unsavedPreference, new PreferenceResponse(inputRecord_8.eeid, inputRecord_8.p1, inputRecord_8.p2, inputRecord_8.p3, inputRecord_8.p4, inputRecord_8.p5, inputRecord_8.p6, inputRecord_8.p7, inputRecord_8.p8, inputRecord_8.p9, inputRecord_8.p10, inputRecord_8.n1, inputRecord_8.n2, inputRecord_8.n3, inputRecord_8.n4, inputRecord_8.n5, inputRecord_8.n6, inputRecord_8.n7, inputRecord_8.n8, inputRecord_8.n9, rank, inputRecord_8.s1, inputRecord_8.s2, inputRecord_8.s3, inputRecord_8.s4, inputRecord_8.s5, inputRecord_8.s6, inputRecord_8.s7, inputRecord_8.s8, inputRecord_8.s9, inputRecord_8.s10, inputRecord_8.upddate, inputRecord_8.comments, inputRecord_8.feedback, inputRecord_8.doc)), model.preferenceEqualList, model.token, model.selectedProject, model.selectedProjectIndex, model.confirmAddProjectModal, model.confirmRemoveProjectModal, model.confirmSaveChangesModal, model.isPreferenceTab), 10, rank];
        default:
            return [model, 10, rank];
    }
}

//# sourceMappingURL=PreferencesHelpers.fs.js.map
